# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='otgadki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_ot', models.CharField(max_length=100)),
                ('text_ot', models.TextField()),
                ('created_date_ot', models.DateTimeField(default=django.utils.timezone.now)),
                ('colprogon', models.IntegerField(default=0, verbose_name='Количество ПРОгонов')),
                ('pop1', models.IntegerField(default=0, verbose_name='Попытка 1-я')),
                ('pop2', models.IntegerField(default=0, verbose_name='Попытка 2-я')),
                ('pop3', models.IntegerField(default=0, verbose_name='Попытка 3-я')),
            ],
        ),
    ]
